### ISSUE TITLE
Error installing on OS X under python 3

### ISSUE THREAD

**Issue by Trii** [Cito/pygresql#4] opened 2017-07-07 18:42 UTC
I am having the same issue this person had
https://stackoverflow.com/questions/37627609/clang-error-when-installing-pygresql-under-mac-os

```
pip3 install PyGreSQL
Collecting PyGreSQL
  Using cached PyGreSQL-5.0.3.tar.gz
Building wheels for collected packages: PyGreSQL
  Running setup.py bdist_wheel for PyGreSQL ... error
  Complete output from command /usr/local/opt/python3/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/sx/vktstng55zj19cp2b0fs82r80000gn/T/pip-build-8je2_lb6/PyGreSQL/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /var/folders/sx/vktstng55zj19cp2b0fs82r80000gn/T/tmp5p2s33jrpip-wheel- --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.12-x86_64-3.6
  copying pg.py -> build/lib.macosx-10.12-x86_64-3.6
  copying pgdb.py -> build/lib.macosx-10.12-x86_64-3.6
  running build_ext
  building '_pg' extension
  creating build/temp.macosx-10.12-x86_64-3.6
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DPYGRESQL_VERSION=5.0.3 -DDIRECT_ACCESS -DLARGE_OBJECTS -DDEFAULT_VARS -DESCAPING_FUNCS -I/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/include/python3.6m -I/usr/local/Cellar/postgresql/9.6.2/include -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c pgmodule.c -o build/temp.macosx-10.12-x86_64-3.6/pgmodule.o -O2 -funsigned-char -Wall -Werror
  pgmodule.c:3694:3: error: code will never be executed [-Werror,-Wunreachable-code]
                  long    num_rows;
                  ^~~~~~~~~~~~~~~~~
  1 error generated.
  error: command 'clang' failed with exit status 1
```
I don't see the same code in `pgmodule.c:3694:3` any more so is this fixed and just not pushed to the cheese shop?

**Comment by Trii** [comment] 2017-07-07 18:46
I get the same error, different line installing from the git https url

`pip3 install https://github.com/Cito/pygresql/zipball/master`

```
    pgmodule.c:3696:3: error: code will never be executed [-Werror,-Wunreachable-code]
                    long    num_rows;
                    ^~~~~~~~~~~~~~~~~
```

**Comment by Cito** [comment] 2017-07-07 21:06
Thanks for reporting. Unfortunately I cannot test on Mac OS and I don't understand why the compiler on Mac OS reports this line as error. The Visual Studio and GCC compilers see no warnings or errors here. Maybe it's a bug or peculiarity of clang?

Does it work if you move the declaration of num_rows and temp from the switch block to a new block inside the case where they are needed, like so?

    switch (PQresultStatus(self->result))
    {
        /* query succeeded */
        case PGRES_TUPLES_OK:  /* DQL: returns None (DB-SIG compliant) */
            self->result_type = RESULT_DQL;
            self->max_row = PQntuples(self->result);
            self->num_fields = PQnfields(self->result);
            Py_INCREF(Py_None);
            return Py_None;
        case PGRES_COMMAND_OK:  /* other requests */
        case PGRES_COPY_OUT:
        case PGRES_COPY_IN:
            {
                long    num_rows;
                char   *temp;
                
                self->result_type = RESULT_DDL;
                temp = PQcmdTuples(self->result);
                num_rows = -1;
                if (temp[0])
                {
                    self->result_type = RESULT_DML;
                    num_rows = atol(temp);
                }
                return PyInt_FromLong(num_rows);
            }
        ...
    }

**Comment by Trii** [comment] 2017-07-07 21:23
That fixes it here.

**Comment by Cito** [comment] 2017-07-08 10:16
Thanks for the feedback. The issue is now fixed in the master branch and the upcoming version 5.0.4.

**Closed by Cito** 2017-07-08 10:16 UTC

**Comment by Trii** [comment] 2017-07-08 12:06
Thank you! I appreciate it.
